import type { LaunchReadinessReport } from "./launch-readiness-audit";

export async function sendAuditReportEmail(
  to: string,
  report: LaunchReadinessReport,
  formattedReport: string,
): Promise<void> {
  const subject = `MasseurMatch Launch Readiness Report - ${new Date(report.generatedAt).toLocaleDateString()}`;

  const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; line-height: 1.6; color: #333; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
    h1 { color: #8B1E2D; border-bottom: 2px solid #8B1E2D; padding-bottom: 10px; }
    h2 { color: #8B1E2D; margin-top: 20px; }
    .summary-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px; margin: 15px 0; }
    .metric-card { background: #f7f7f7; padding: 15px; border-radius: 8px; }
    .metric-value { font-size: 24px; font-weight: bold; color: #8B1E2D; }
    .metric-label { font-size: 12px; color: #666; text-transform: uppercase; letter-spacing: 0.5px; }
    .alert { padding: 15px; border-radius: 8px; margin: 10px 0; }
    .alert-critical { background: #fff5f5; border-left: 4px solid #d32f2f; }
    .alert-warning { background: #fffbf0; border-left: 4px solid #f57c00; }
    .alert-success { background: #f1f8f5; border-left: 4px solid #388e3c; }
    .recommendation { padding: 10px; margin: 5px 0; background: #fafafa; border-left: 3px solid #ddd; }
    .footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #666; }
  </style>
</head>
<body>
  <div class="container">
    <h1>🚀 Launch Readiness Audit Report</h1>
    <p><strong>Generated:</strong> ${new Date(report.generatedAt).toLocaleString()}</p>

    <h2>Summary</h2>
    <div class="summary-grid">
      <div class="metric-card">
        <div class="metric-label">Total Profiles</div>
        <div class="metric-value">${report.summary.totalProfiles}</div>
      </div>
      <div class="metric-card">
        <div class="metric-label">Verified</div>
        <div class="metric-value">${report.summary.verifiedProfiles}</div>
      </div>
      <div class="metric-card">
        <div class="metric-label">Indexable</div>
        <div class="metric-value">${report.summary.indexableProfiles}</div>
      </div>
      <div class="metric-card">
        <div class="metric-label">Readiness</div>
        <div class="metric-value">${report.summary.readinessPercentage}%</div>
      </div>
    </div>

    <h2>Quality Metrics</h2>
    <ul>
      <li>Profile Photos: <strong>${report.qualityMetrics.profilePhotoCompletion}%</strong></li>
      <li>Descriptions: <strong>${report.qualityMetrics.descriptionCompletion}%</strong></li>
      <li>Pricing: <strong>${report.qualityMetrics.pricingCompletion}%</strong></li>
      <li>Verification: <strong>${report.qualityMetrics.verificationCompletion}%</strong></li>
      <li>Avg Photos/Profile: <strong>${report.qualityMetrics.averagePhotosPerProfile}</strong></li>
    </ul>

    ${report.qualityMetrics.profilesWithoutContact > 0 ? `
    <div class="alert alert-warning">
      ⚠️ ${report.qualityMetrics.profilesWithoutContact} profiles missing contact info
    </div>
    ` : ""}

    ${report.qualityMetrics.profilesWithoutServices > 0 ? `
    <div class="alert alert-warning">
      ⚠️ ${report.qualityMetrics.profilesWithoutServices} profiles missing services
    </div>
    ` : ""}

    <h2>Recommendations</h2>
    ${report.recommendations.map((rec) => {
      let alertClass = "alert-success";
      if (rec.includes("🔴")) alertClass = "alert-critical";
      else if (rec.includes("🟡")) alertClass = "alert-warning";

      return `<div class="alert ${alertClass}">${rec}</div>`;
    }).join("")}

    <h2>Cities Overview</h2>
    <ul>
      ${Object.entries(report.byCity).map(([_, audit]) => `
        <li>
          <strong>${audit.cityName}</strong>: ${audit.profileCount} profiles
          (${audit.verifiedCount} verified, ${audit.indexableCount} indexable)
          ${audit.isLive ? "🟢 LIVE" : "🔲 Not Live"}
          ${audit.missingProfiles > 0 ? `- Needs ${audit.missingProfiles} more` : ""}
        </li>
      `).join("")}
    </ul>

    <div class="footer">
      <p>This report was automatically generated by the MasseurMatch launch readiness system.</p>
      <p>Log in to the admin dashboard to view detailed breakdowns and take action on recommendations.</p>
    </div>
  </div>
</body>
</html>
  `;

  const plainTextContent = formattedReport;

  try {
    const response = await fetch(`${process.env.NEXT_PUBLIC_SITE_URL || "https://masseurmatch.com"}/api/email/send`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        to,
        subject,
        html: htmlContent,
        text: plainTextContent,
      }),
    });

    if (!response.ok) {
      throw new Error(`Email service returned ${response.status}`);
    }
  } catch (error) {
    console.error("[Audit Report Email] Failed to send:", error);
    throw error;
  }
}
