import type { PublicTherapist } from "@/app/_lib/directory";

type FallbackTherapist = Omit<PublicTherapist, 'id' | 'slug'> & {
  id: string;
  slug: string;
  [key: string]: any;
};

const FUTURE_DATE = "2026-12-31T23:59:59.000Z";

export const FALLBACK_PUBLIC_THERAPISTS: FallbackTherapist[] = [
  {
    id: "fallback-ethan-cole",
    slug: "ethan-cole",
    city: "Dallas",
    state: "TX",
    display_name: "Ethan Cole",
    full_name: "Ethan Cole",
    headline: "Premium Deep Tissue & Relaxation in Uptown",
    bio: "Ethan works from Uptown Dallas with a premium, confidence-first flow built around deep tissue, relaxation, and responsive same-day communication.",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80",
    phone: "+1 (214) 555-0101",
    whatsapp_number: null,
    email_address: null,
    website: null,
    service_categories: ["Massage"],
    massage_techniques: ["Deep Tissue", "Swedish"],
    specialties: ["Relaxation", "Deep Tissue"],
    _tier: "elite",
    subscription_tier: "elite",
    modality: "Deep Tissue",
    status: "approved",
    profile_status: "approved",
    visibility_status: "public",
    profile_views: 621,
    review_count: 28,
    incall_price: 120,
    outcall_price: 150,
    starting_price: 120,
    business_hours: null,
    custom_faq: null,
    pricing_sessions: null,
    available_now: true,
    available_now_expires: FUTURE_DATE,
    verification_status: "verified",
    is_verified_identity: true,
    is_verified_profile: true,
    is_verified_photos: true,
    neighborhood: "Uptown",
    neighborhood_name: "Uptown Dallas",
    primary_area: "Uptown",
    years_experience: 6,
    start_year: null,
    latitude: 32.8007,
    longitude: -96.8035,
    zip_code: "75204",
    special_offer_text: null,
    is_featured: true,
    updated_at: new Date().toISOString(),
  },
  {
    id: "fallback-mason-ellis",
    slug: "mason-ellis",
    city: "Dallas",
    state: "TX",
    display_name: "Mason Ellis",
    full_name: "Mason Ellis",
    headline: "Recovery-Focused Bodywork in Oak Lawn",
    bio: "Mason is based near Oak Lawn and focuses on recovery-led bodywork with clear incall and outcall options for clients who want less guesswork before booking.",
    avatar_url: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=900&q=80",
    phone: "+1 (214) 555-0102",
    whatsapp_number: null,
    email_address: null,
    website: null,
    service_categories: ["Massage"],
    massage_techniques: ["Sports", "Deep Tissue"],
    specialties: ["Sports Recovery", "Deep Tissue"],
    _tier: "pro",
    subscription_tier: "pro",
    modality: "Sports Recovery",
    status: "approved",
    profile_status: "approved",
    visibility_status: "public",
    profile_views: 488,
    review_count: 19,
    incall_price: 110,
    outcall_price: 140,
    starting_price: 110,
    business_hours: null,
    custom_faq: null,
    pricing_sessions: null,
    available_now: true,
    available_now_expires: FUTURE_DATE,
    verification_status: "verified",
    is_verified_identity: true,
    is_verified_profile: true,
    is_verified_photos: true,
    neighborhood: "Oak Lawn",
    neighborhood_name: "Oak Lawn",
    primary_area: "Central Dallas",
    years_experience: 8,
    start_year: null,
    latitude: 32.8112,
    longitude: -96.8121,
    zip_code: "75219",
    special_offer_text: "10% off weekday recovery sessions",
    is_featured: true,
    updated_at: new Date().toISOString(),
  },
  {
    id: "fallback-owen-parker",
    slug: "owen-parker",
    city: "Dallas",
    state: "TX",
    display_name: "Owen Parker",
    full_name: "Owen Parker",
    headline: "Therapeutic Stretch & Bodywork",
    bio: "Owen keeps his profile simple and approachable for clients who want therapeutic stretch work, a straightforward studio setup, and visible starting rates.",
    avatar_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=900&q=80",
    phone: "+1 (214) 555-0103",
    whatsapp_number: null,
    email_address: null,
    website: null,
    service_categories: ["Massage"],
    massage_techniques: ["Stretch", "Therapeutic"],
    specialties: ["Stretch Therapy", "Therapeutic Massage"],
    _tier: "standard",
    subscription_tier: "standard",
    modality: "Stretch Therapy",
    status: "approved",
    profile_status: "approved",
    visibility_status: "public",
    profile_views: 177,
    review_count: 8,
    incall_price: 95,
    outcall_price: null,
    starting_price: 95,
    business_hours: null,
    custom_faq: null,
    pricing_sessions: null,
    available_now: false,
    available_now_expires: null,
    verification_status: "verified",
    is_verified_identity: true,
    is_verified_profile: true,
    is_verified_photos: false,
    neighborhood: "Medical District",
    neighborhood_name: "Medical District",
    primary_area: "North Dallas",
    years_experience: 3,
    start_year: null,
    latitude: 32.8105,
    longitude: -96.8413,
    zip_code: "75235",
    special_offer_text: null,
    is_featured: false,
    updated_at: new Date().toISOString(),
  },
  {
    id: "fallback-kevin-os",
    slug: "kevin-os",
    city: "Carrollton",
    state: "TX",
    display_name: "KevinOS",
    full_name: "KevinOS",
    headline: "Deep Tissue & Acupressure Specialist",
    bio: "Certified massage therapist with over 8 years of experience. Offering deep tissue, acupressure, and head massage in a relaxing environment with music and aromatherapy.",
    avatar_url: null,
    phone: null,
    whatsapp_number: null,
    email_address: null,
    website: null,
    service_categories: ["Massage"],
    massage_techniques: ["Deep Tissue", "Acupressure"],
    specialties: ["Deep Tissue", "Acupressure", "Therapeutic", "Head Massage"],
    _tier: "pro",
    subscription_tier: "pro",
    modality: "Deep Tissue",
    status: "approved",
    profile_status: "approved",
    visibility_status: "public",
    profile_views: 320,
    review_count: 58,
    incall_price: null,
    outcall_price: null,
    starting_price: null,
    business_hours: null,
    custom_faq: null,
    pricing_sessions: null,
    available_now: true,
    available_now_expires: FUTURE_DATE,
    verification_status: "verified",
    is_verified_identity: true,
    is_verified_profile: true,
    is_verified_photos: false,
    neighborhood: "Carrollton",
    neighborhood_name: "Carrollton",
    primary_area: "Dallas Metro",
    years_experience: 8,
    start_year: null,
    latitude: 32.9537,
    longitude: -96.8899,
    zip_code: null,
    special_offer_text: null,
    is_featured: false,
    updated_at: new Date().toISOString(),
  },
  {
    id: "fallback-bruno-santos",
    slug: "bruno-dallas-tx",
    city: "Dallas",
    state: "TX",
    display_name: "Bruno",
    full_name: "Bruno Santos",
    headline: "14 Years Experience in Deep Tissue & Recovery",
    bio: "Brazilian-trained therapist with 14 years of experience in Oak Lawn, Dallas. Specializes in Deep Tissue, Swedish, Hot Stone, Shiatsu, AMMA Therapy, Lymphatic Drainage, Myofascial Release, and Zero Balancing.",
    avatar_url: null,
    phone: "+17623345300",
    whatsapp_number: null,
    email_address: null,
    website: null,
    service_categories: ["Massage"],
    massage_techniques: ["Deep Tissue", "Swedish", "Hot Stone"],
    specialties: ["Deep Tissue", "Swedish", "Hot Stone", "Shiatsu", "AMMA Therapy", "Lymphatic Drainage", "Myofascial Release", "Zero Balancing"],
    _tier: "elite",
    subscription_tier: "elite",
    modality: "Deep Tissue",
    status: "approved",
    profile_status: "approved",
    visibility_status: "public",
    profile_views: 512,
    review_count: 12,
    incall_price: 175,
    outcall_price: null,
    starting_price: 175,
    business_hours: null,
    custom_faq: null,
    pricing_sessions: [
      { name: "60 min", duration: 60, incall: 175 },
      { name: "90 min", duration: 90, incall: 250 },
    ],
    available_now: true,
    available_now_expires: FUTURE_DATE,
    verification_status: "verified",
    is_verified_identity: true,
    is_verified_profile: true,
    is_verified_photos: true,
    neighborhood: "Oak Lawn",
    neighborhood_name: "Oak Lawn",
    primary_area: "Central Dallas",
    years_experience: 14,
    start_year: null,
    latitude: 32.8112,
    longitude: -96.8121,
    zip_code: "75219",
    special_offer_text: "10% off Mondays",
    is_featured: true,
    updated_at: new Date().toISOString(),
  },
  {
    id: "fallback-leo-martinez",
    slug: "leo-martinez",
    city: "Austin",
    state: "TX",
    display_name: "Leo Martinez",
    full_name: "Leo Martinez",
    headline: "Bilingual Deep Tissue & Mobility Expert",
    bio: "Leo anchors Austin discovery with polished profile depth, bilingual communication, and a blend of lymphatic, deep tissue, and mobility-focused care.",
    avatar_url: "https://images.unsplash.com/photo-1500048993953-d23a436266cf?auto=format&fit=crop&w=900&q=80",
    phone: "+1 (512) 555-0104",
    whatsapp_number: null,
    email_address: null,
    website: null,
    service_categories: ["Massage"],
    massage_techniques: ["Lymphatic", "Deep Tissue"],
    specialties: ["Lymphatic", "Deep Tissue"],
    _tier: "elite",
    subscription_tier: "elite",
    modality: "Lymphatic",
    status: "approved",
    profile_status: "approved",
    visibility_status: "public",
    profile_views: 563,
    review_count: 33,
    incall_price: 125,
    outcall_price: 165,
    starting_price: 125,
    business_hours: null,
    custom_faq: null,
    pricing_sessions: null,
    available_now: false,
    available_now_expires: null,
    verification_status: "verified",
    is_verified_identity: true,
    is_verified_profile: true,
    is_verified_photos: true,
    neighborhood: "South Congress",
    neighborhood_name: "South Congress",
    primary_area: "Central Austin",
    years_experience: 7,
    start_year: null,
    latitude: 30.2495,
    longitude: -97.7495,
    zip_code: "78704",
    special_offer_text: "Complimentary add-on stretch for first-time clients",
    is_featured: true,
    updated_at: new Date().toISOString(),
  },
  {
    id: "fallback-adrian-cole",
    slug: "adrian-cole",
    city: "Houston",
    state: "TX",
    display_name: "Adrian Cole",
    full_name: "Adrian Cole",
    headline: "Thai & Mobility Specialist in Montrose",
    bio: "Adrian serves Montrose and Downtown Houston with Thai, deep tissue, and mobility work for clients who want a modern, premium discovery experience.",
    avatar_url: "https://images.unsplash.com/photo-1504593811423-6dd665756598?auto=format&fit=crop&w=900&q=80",
    phone: "+1 (713) 555-0105",
    whatsapp_number: null,
    email_address: null,
    website: null,
    service_categories: ["Massage"],
    massage_techniques: ["Thai", "Deep Tissue"],
    specialties: ["Thai Massage", "Recovery"],
    _tier: "pro",
    subscription_tier: "pro",
    modality: "Thai Massage",
    status: "approved",
    profile_status: "approved",
    visibility_status: "public",
    profile_views: 349,
    review_count: 21,
    incall_price: 115,
    outcall_price: 155,
    starting_price: 115,
    business_hours: null,
    custom_faq: null,
    pricing_sessions: null,
    available_now: true,
    available_now_expires: FUTURE_DATE,
    verification_status: "verified",
    is_verified_identity: true,
    is_verified_profile: true,
    is_verified_photos: true,
    neighborhood: "Montrose",
    neighborhood_name: "Montrose",
    primary_area: "Inner Loop",
    years_experience: 5,
    start_year: null,
    latitude: 29.7487,
    longitude: -95.3906,
    zip_code: "77006",
    special_offer_text: null,
    is_featured: true,
    updated_at: new Date().toISOString(),
  },
  {
    id: "fallback-jordan-brooks",
    slug: "jordan-brooks",
    city: "Houston",
    state: "TX",
    display_name: "Jordan Brooks",
    full_name: "Jordan Brooks",
    headline: "Relaxing Swedish Massage in Downtown",
    bio: "Jordan keeps the experience warm and low-pressure with relaxation sessions, evening availability, and a studio setup that feels easy to say yes to quickly.",
    avatar_url: "https://images.unsplash.com/photo-1507591064344-4c6ce005b128?auto=format&fit=crop&w=900&q=80",
    phone: "+1 (713) 555-0106",
    whatsapp_number: null,
    email_address: null,
    website: null,
    service_categories: ["Massage"],
    massage_techniques: ["Swedish", "Relaxation"],
    specialties: ["Relaxation", "Swedish"],
    _tier: "standard",
    subscription_tier: "standard",
    modality: "Relaxation",
    status: "approved",
    profile_status: "approved",
    visibility_status: "public",
    profile_views: 214,
    review_count: 14,
    incall_price: 100,
    outcall_price: null,
    starting_price: 100,
    business_hours: null,
    custom_faq: null,
    pricing_sessions: null,
    available_now: false,
    available_now_expires: null,
    verification_status: "verified",
    is_verified_identity: true,
    is_verified_profile: true,
    is_verified_photos: false,
    neighborhood: "Downtown",
    neighborhood_name: "Downtown Houston",
    primary_area: "Downtown",
    years_experience: 4,
    start_year: null,
    latitude: 29.7604,
    longitude: -95.3698,
    zip_code: "77002",
    special_offer_text: "Late evening rate from $100",
    is_featured: false,
    updated_at: new Date().toISOString(),
  },
  {
    id: "fallback-nico-hayes",
    slug: "nico-hayes",
    city: "Chicago",
    state: "IL",
    display_name: "Nico Hayes",
    full_name: "Nico Hayes",
    headline: "Elite Sports Recovery in River North",
    bio: "Nico is built for clients comparing same-day availability, downtown proximity, and premium recovery work before opening a profile.",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80",
    phone: "+1 (312) 555-0107",
    whatsapp_number: null,
    email_address: null,
    website: null,
    service_categories: ["Massage"],
    massage_techniques: ["Sports", "Deep Tissue"],
    specialties: ["Sports Recovery", "Deep Tissue"],
    _tier: "elite",
    subscription_tier: "elite",
    modality: "Sports Recovery",
    status: "approved",
    profile_status: "approved",
    visibility_status: "public",
    profile_views: 432,
    review_count: 25,
    incall_price: 130,
    outcall_price: 160,
    starting_price: 130,
    business_hours: null,
    custom_faq: null,
    pricing_sessions: null,
    available_now: true,
    available_now_expires: FUTURE_DATE,
    verification_status: "verified",
    is_verified_identity: true,
    is_verified_profile: true,
    is_verified_photos: true,
    neighborhood: "River North",
    neighborhood_name: "River North",
    primary_area: "Downtown Chicago",
    years_experience: 9,
    start_year: null,
    latitude: 41.8924,
    longitude: -87.6341,
    zip_code: "60654",
    special_offer_text: null,
    is_featured: true,
    updated_at: new Date().toISOString(),
  },
  {
    id: "fallback-blake-vance",
    slug: "blake-vance",
    city: "Chicago",
    state: "IL",
    display_name: "Blake Vance",
    full_name: "Blake Vance",
    headline: "Professional Swedish & Deep Tissue in West Loop",
    bio: "Blake serves the West Loop with Swedish and deep tissue work, focusing on a clean studio environment and straightforward booking for busy professionals.",
    avatar_url: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=900&q=80",
    phone: "+1 (312) 555-0108",
    whatsapp_number: null,
    email_address: null,
    website: null,
    service_categories: ["Massage"],
    massage_techniques: ["Swedish", "Deep Tissue"],
    specialties: ["Swedish", "Deep Tissue"],
    _tier: "pro",
    subscription_tier: "pro",
    modality: "Swedish",
    status: "approved",
    profile_status: "approved",
    visibility_status: "public",
    profile_views: 287,
    review_count: 12,
    incall_price: 110,
    outcall_price: 145,
    starting_price: 110,
    business_hours: null,
    custom_faq: null,
    pricing_sessions: null,
    available_now: false,
    available_now_expires: null,
    verification_status: "verified",
    is_verified_identity: true,
    is_verified_profile: true,
    is_verified_photos: true,
    neighborhood: "West Loop",
    neighborhood_name: "West Loop",
    primary_area: "West Side",
    years_experience: 5,
    start_year: null,
    latitude: 41.8826,
    longitude: -87.6483,
    zip_code: "60661",
    special_offer_text: "First-time client discount available",
    is_featured: true,
    updated_at: new Date().toISOString(),
  }
];
