import { z } from "zod";

// Schema for the complete massage therapist profile
export const massageTherapistProfileSchema = z.object({
    heightInches: z.number().int().min(48).max(96).nullable().optional(),
    weightLb: z.number().int().min(80).max(450).nullable().optional(),
    bodyType: z.string().max(60).nullable().optional(),
  full_name: z.string().min(2).max(80),
  display_name: z.string().min(2).max(80),
  headline: z.string().max(120),
  bio_short: z.string().max(300),
  bio_full: z.string().max(4000),
  experience_start: z.string(),
  languages: z.array(z.string()),
  city: z.string().max(120),
  state: z.string().max(120),
  neighborhood: z.string().max(120),
  location_description: z.string().max(300),
  zip_code: z.string().optional(),
  is_mappable: z.boolean(),
  landmarks: z.array(z.string()),
  offers_incall: z.boolean(),
  offers_outcall: z.boolean(),
  outcall_radius: z.number().optional(),
  service_area_cities: z.array(z.string()),
  massage_techniques: z.array(z.string()),
  specialties: z.array(z.string()),
  massage_setup: z.array(z.string()),
  mobile_extras: z.array(z.string()),
  incall_amenities: z.array(z.string()),
  additional_services: z.array(z.string()),
  products_used: z.array(z.string()),
  products_sold: z.array(z.string()),
  starting_rate: z.number(),
  rates_incall: z.array(z.object({ duration_minutes: z.number(), price: z.number(), display_note: z.string().optional() })),
  rates_outcall: z.array(z.object({ duration_minutes: z.number(), price_or_label: z.string(), display_note: z.string().optional() })),
  discounts: z.string().optional(),
  weekly_specials: z.string().optional(),
  rate_disclaimer: z.string().optional(),
  payment_methods: z.array(z.string()),
  incall_hours: z.record(z.object({ enabled: z.boolean(), start: z.string(), end: z.string() })),
  outcall_hours: z.record(z.object({ enabled: z.boolean(), start: z.string(), end: z.string() })),
  available_now: z.boolean(),
  available_today: z.boolean(),
  same_day_booking: z.boolean(),
  is_traveling: z.boolean(),
  travel_cities: z.array(z.string()),
  travel_dates: z.object({ start: z.string(), end: z.string() }).optional(),
  travel_note: z.string().optional(),
  years_experience: z.number(),
  education: z.array(z.object({ school_name: z.string(), program_name: z.string(), city: z.string(), country: z.string(), start_date: z.string(), end_date: z.string() })),
  licenses: z.array(z.object({ title: z.string(), issuer: z.string(), year: z.string() })),
  affiliations: z.array(z.string()),
  phone_number: z.string(),
  show_email_button: z.boolean(),
  email_address: z.string().optional(),
  booking_link: z.string().optional(),
  whatsapp_number: z.string().optional(),
  telegram_handle: z.string().optional(),
  profile_photo: z.string(),
  gallery_photos: z.array(z.string()),
  cover_photo: z.string().optional(),
  video_intro: z.string().optional(),
  tier: z.enum(["Free", "Standard", "Pro", "Elite"]),
  is_verified_profile: z.boolean(),
  lgbtq_friendly: z.boolean(),
  visiting_soon: z.boolean(),
  top_rated: z.boolean(),
  seo_title: z.string().optional(),
  seo_description: z.string().optional(),
  seo_keywords: z.array(z.string()).optional(),
  slug: z.string(),
  canonical_city: z.string().optional(),
});
