import { z } from "zod";

const optionalString = z.string().trim().max(4000).optional().nullable();
const optionalNumber = z.number().finite().optional().nullable();
const optionalBoolean = z.boolean().optional().default(false);
const stringArray = z.array(z.string().trim().max(120)).optional().default([]);

export const massageTherapistProfileSchema = z.object({
  full_name: optionalString,
  display_name: z.string().trim().min(2).max(80),
  headline: optionalString,
  bio_short: optionalString,
  bio_full: z.string().trim().min(10).max(4000),
  experience_start: optionalString,
  languages: stringArray,
  city: z.string().trim().min(2).max(120),
  state: optionalString,
  neighborhood: optionalString,
  location_description: optionalString,
  zip_code: optionalString,
  is_mappable: optionalBoolean,
  landmarks: stringArray,
  offers_incall: optionalBoolean,
  offers_outcall: optionalBoolean,
  outcall_radius: optionalNumber,
  service_area_cities: stringArray,
  massage_techniques: stringArray,
  specialties: stringArray,
  massage_setup: stringArray,
  mobile_extras: stringArray,
  incall_amenities: stringArray,
  additional_services: stringArray,
  products_used: stringArray,
  products_sold: stringArray,
  starting_rate: optionalNumber,
  rates_incall: z.array(z.object({ duration_minutes: z.number(), price: z.number(), display_note: optionalString })).optional().default([]),
  rates_outcall: z.array(z.object({ duration_minutes: z.number(), price_or_label: z.string(), display_note: optionalString })).optional().default([]),
  discounts: optionalString,
  weekly_specials: optionalString,
  rate_disclaimer: optionalString,
  payment_methods: stringArray,
  incall_hours: z.record(z.object({ enabled: z.boolean(), start: z.string(), end: z.string() })).optional().default({}),
  outcall_hours: z.record(z.object({ enabled: z.boolean(), start: z.string(), end: z.string() })).optional().default({}),
  available_now: optionalBoolean,
  available_today: optionalBoolean,
  same_day_booking: optionalBoolean,
  is_traveling: optionalBoolean,
  travel_cities: stringArray,
  travel_dates: z.object({ start: z.string(), end: z.string() }).optional().nullable(),
  travel_note: optionalString,
  years_experience: optionalNumber,
  education: z.array(z.object({ school_name: z.string(), program_name: z.string(), city: z.string(), country: z.string(), start_date: z.string(), end_date: z.string() })).optional().default([]),
  licenses: z.array(z.object({ title: z.string(), issuer: z.string(), year: z.string() })).optional().default([]),
  affiliations: stringArray,
  phone_number: optionalString,
  show_email_button: optionalBoolean,
  email_address: optionalString,
  booking_link: optionalString,
  whatsapp_number: optionalString,
  telegram_handle: optionalString,
  profile_photo: optionalString,
  gallery_photos: z.array(z.string()).optional().default([]),
  cover_photo: optionalString,
  video_intro: optionalString,
  tier: z.enum(["Free", "Standard", "Pro", "Elite"]).optional().default("Free"),
  is_verified_profile: optionalBoolean,
  lgbtq_friendly: optionalBoolean,
  visiting_soon: optionalBoolean,
  top_rated: optionalBoolean,
  seo_title: optionalString,
  seo_description: optionalString,
  seo_keywords: stringArray,
  slug: optionalString,
  canonical_city: optionalString,

  displayName: z.string().trim().min(2).max(80).optional(),
  bio: z.string().trim().min(10).max(4000).optional(),
  phone: optionalString,
  incallPrice: optionalNumber,
  outcallPrice: optionalNumber,
  heightInches: z.number().int().min(48).max(96).nullable().optional(),
  weightLb: z.number().int().min(80).max(450).nullable().optional(),
  bodyType: optionalString,
}).transform((data) => ({
  ...data,
  display_name: data.display_name || data.displayName || "",
  bio_full: data.bio_full || data.bio || "",
  phone_number: data.phone_number || data.phone || null,
  starting_rate: data.starting_rate ?? data.incallPrice ?? data.outcallPrice ?? null,
  heightInches: data.heightInches ?? null,
  weightLb: data.weightLb ?? null,
  bodyType: data.bodyType ?? null,
}));
