"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, Bell, CalendarDays, Loader2, LockKeyhole, MapPin, Radar, RefreshCw, TrendingUp, Zap } from "lucide-react";
import { formatUsDate, getDemandLabel, getSpikeLabel, getSpikeWindow, type DataFreshness, type DemandTrend } from "@/lib/demand-radar";

type RadarRow = { id:string; city:string; state:string; neighborhood:string|null; score:number; trend:DemandTrend; spike_score?:number|null; week_start:string; collected_at:string|null; search_volume_index?:number; competition_index?:number; confidence?:number|null; source?:string|null; opportunity_score?:number };
type RadarResponse = { ok:boolean; access:{tier:string;full:boolean;preview:boolean}; market:{city:string|null;state:string|null;weekStart:string|null;freshness:DataFreshness;collectedAt:string|null}; local:RadarRow[]; opportunities:RadarRow[]; disclaimer:string; error?:string };
const freshnessCopy:Record<DataFreshness,string>={fresh:"Fresh data",delayed:"Delayed data",stale:"Stale data",unknown:"Awaiting data"};
function trendCopy(t:DemandTrend){return t==="rising"?"Rising":t==="falling"?"Falling":"Stable"}
function ScoreCard({label,value,detail}:{label:string;value:string|number;detail:string}){return <div className="rounded-2xl border border-[#E8DFD8] bg-white p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#81766F]">{label}</p><p className="mt-3 font-display text-3xl font-semibold text-[#211C19]">{value}</p><p className="mt-1 text-xs text-[#756C66]">{detail}</p></div>}
function UpgradeCard(){return <div className="rounded-3xl border border-[#E4D8D1] bg-[#FCF8F5] p-6 shadow-sm"><div className="flex items-start gap-4"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-[#F9EDEE] text-[#8B1E2D]"><LockKeyhole className="h-5 w-5"/></div><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#8B1E2D]">Elite intelligence</p><h2 className="mt-1 font-display text-xl font-semibold">Unlock the full Demand Radar</h2><p className="mt-2 text-sm text-[#716862]">See spike intensity, timing, opportunity, competition, confidence and full market rankings.</p><Link href="/pro/subscription" className="mt-4 inline-flex items-center gap-2 rounded-xl bg-[#8B1E2D] px-4 py-2.5 text-sm font-semibold text-white">View Elite plan <ArrowUpRight className="h-4 w-4"/></Link></div></div></div>}

export default function DemandRadarPage(){
 const [data,setData]=useState<RadarResponse|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
 async function load(){setLoading(true);setError(null);try{const r=await fetch("/api/pro/demand-radar",{cache:"no-store"});const p=await r.json() as RadarResponse;if(!r.ok){setData(p);setError(p.error??"Demand Radar could not be loaded.");return}setData(p)}catch{setError("Demand Radar could not be loaded.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]); const localPrimary=useMemo(()=>data?.local.find(r=>!r.neighborhood)??data?.local[0]??null,[data]);
 if(loading)return <div className="flex min-h-[60vh] items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-[#8B1E2D]"/></div>;
 if(error||!data)return <div className="mx-auto max-w-3xl p-8"><div className="rounded-2xl border border-rose-200 bg-rose-50 p-6"><p className="font-semibold text-rose-900">Demand Radar unavailable</p><p className="mt-1 text-sm text-rose-700">{error}</p><button onClick={()=>void load()} className="mt-4 inline-flex items-center gap-2 text-sm font-semibold"><RefreshCw className="h-4 w-4"/>Retry</button></div></div>;
 const isPreview=data.access.preview&&!data.access.full;
 const bestSignal=(localPrimary??data.opportunities[0]??null); const bestWindow=bestSignal?getSpikeWindow(bestSignal):null;
 return <div className="mx-auto max-w-6xl space-y-6 p-4 pb-24 md:p-8">
  <header className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><div className="flex items-center gap-2 text-[#8B1E2D]"><Radar className="h-5 w-5"/><span className="text-xs font-bold uppercase tracking-[0.16em]">{isPreview?"Market Intelligence Preview":"Elite Market Intelligence"}</span></div><h1 className="mt-2 font-display text-3xl font-semibold">Demand Radar</h1><p className="mt-2 max-w-2xl text-sm text-[#716862]">Know where demand is accelerating, when the signal is strongest, and what to do next.</p></div><button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-2.5 text-sm font-semibold"><RefreshCw className="h-4 w-4"/>Refresh</button></header>

  <div className="rounded-2xl border bg-[#FCF8F5] px-4 py-3 text-xs text-[#6D625B]">{freshnessCopy[data.market.freshness]}{data.market.collectedAt?` · Updated ${formatUsDate(data.market.collectedAt)}`:""}{data.market.weekStart?` · Week of ${formatUsDate(data.market.weekStart)}`:""}</div>

  {bestSignal&&bestWindow?<section className="rounded-3xl border border-[#E4D8D1] bg-white p-6 shadow-sm"><div className="flex items-center gap-2 text-[#8B1E2D]"><TrendingUp className="h-5 w-5"/><p className="text-xs font-bold uppercase tracking-[0.14em]">Your clearest signal</p></div><div className="mt-5 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-[#FCF8F5] p-5"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-[#81766F]"><MapPin className="h-4 w-4"/>Where</div><p className="mt-3 font-display text-2xl font-semibold">{bestSignal.city}, {bestSignal.state}</p></div><div className="rounded-2xl bg-[#FCF8F5] p-5"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-[#81766F]"><CalendarDays className="h-4 w-4"/>When</div><p className="mt-3 text-lg font-semibold">{bestWindow.start&&bestWindow.end?`${formatUsDate(bestWindow.start)} – ${formatUsDate(bestWindow.end)}`:"No confirmed window"}</p><p className="mt-1 text-xs text-[#756C66]">{bestWindow.label}</p></div><div className="rounded-2xl bg-[#FCF8F5] p-5"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-[#81766F]"><Zap className="h-4 w-4"/>Signal</div><p className="mt-3 font-display text-2xl font-semibold">{getSpikeLabel(bestSignal.spike_score)}</p><p className="mt-1 text-xs text-[#756C66]">Spike {bestSignal.spike_score??"—"}/100 · Confidence {bestSignal.confidence??"—"}/100</p></div></div><div className="mt-4 rounded-2xl border border-[#E9E0DA] p-4 text-sm text-[#5F5650]"><strong>What to do:</strong> {bestWindow.action}</div>{!isPreview&&bestWindow.status==="active"?<div className="mt-4 flex items-center gap-2 text-xs text-[#6D625B]"><Bell className="h-4 w-4 text-[#8B1E2D]"/>Email alerts are sent when a confirmed high-confidence spike is detected in your profile city and market-insight emails are enabled.</div>:null}</section>:null}

  {localPrimary?<section className="space-y-4"><div className="flex items-center gap-2"><MapPin className="h-4 w-4 text-[#8B1E2D]"/><h2 className="font-display text-xl font-semibold">Your market: {localPrimary.city}, {localPrimary.state}</h2></div>{isPreview?<div className="grid gap-4 sm:grid-cols-3"><ScoreCard label="Demand" value={getDemandLabel(localPrimary.score)} detail={`${localPrimary.score}/100`}/><ScoreCard label="Spike" value={getSpikeLabel(localPrimary.spike_score)} detail={localPrimary.spike_score==null?"Awaiting baseline":`${localPrimary.spike_score}/100 acceleration`}/><ScoreCard label="Trend" value={trendCopy(localPrimary.trend)} detail="Direction versus recent baseline"/></div>:<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><ScoreCard label="Demand" value={localPrimary.score} detail={getDemandLabel(localPrimary.score)}/><ScoreCard label="Spike" value={localPrimary.spike_score??"—"} detail={getSpikeLabel(localPrimary.spike_score)}/><ScoreCard label="Opportunity" value={localPrimary.opportunity_score??"—"} detail="Demand adjusted for competition"/><ScoreCard label="Competition" value={localPrimary.competition_index??"—"} detail="Lower can mean more room"/><ScoreCard label="Confidence" value={localPrimary.confidence??"—"} detail={trendCopy(localPrimary.trend)}/></div>}</section>:null}
  {isPreview?<UpgradeCard/>:null}

  <section className="rounded-3xl border bg-white shadow-sm"><div className="flex items-center gap-3 border-b px-6 py-5"><Radar className="h-5 w-5 text-[#8B1E2D]"/><div><h2 className="font-display text-lg font-semibold">{isPreview?"Market preview":"Where spikes are happening"}</h2><p className="text-xs text-[#756C66]">Markets ranked by opportunity with a simple 7-day signal window</p></div></div>{data.opportunities.length===0?<div className="p-8 text-center text-sm">No live demand data has been ingested yet.</div>:<div className="divide-y">{data.opportunities.map((row,i)=>{const window=getSpikeWindow(row);return <div key={row.id} className="grid gap-4 px-6 py-4 md:grid-cols-[44px_1.4fr_repeat(3,minmax(110px,1fr))] md:items-center"><div className="font-display text-lg text-[#A59A92]">{i+1}</div><div><p className="font-semibold">{row.city}, {row.state}</p><p className="mt-1 text-xs text-[#7A716B]">{trendCopy(row.trend)} · {getSpikeLabel(row.spike_score)}</p></div><div><p className="text-xs text-[#8A817B]">When</p><p className="text-sm font-semibold">{window.start&&window.end?`${formatUsDate(window.start)} – ${formatUsDate(window.end)}`:"No confirmed window"}</p></div><div><p className="text-xs text-[#8A817B]">Demand</p><p className="font-semibold">{isPreview?getDemandLabel(row.score):`${row.score}/100`}</p></div><div><p className="text-xs text-[#8A817B]">Spike / Confidence</p><p className="font-semibold">{isPreview?getSpikeLabel(row.spike_score):`${row.spike_score??"—"} / ${row.confidence??"—"}`}</p></div></div>})}</div>}</section>
  <p className="text-xs leading-5 text-[#7B726C]">{data.disclaimer} Spike windows describe current acceleration observed in fresh market data; they are statistical signals, not guaranteed future bookings or exact search volumes.</p>
 </div>
}
