// Field definitions for the onboarding/profile forms
export const MASSAGE_THERAPIST_FIELDS = {
  full_name: {
    label: 'Full Name',
    type: 'text',
    placeholder: 'Bruno',
    public: true,
  },
  display_name: {
    label: 'Display Name',
    type: 'text',
    placeholder: 'Bruno Massage Therapy',
    public: true,
  },
  headline: {
    label: 'Headline',
    type: 'text',
    placeholder: 'Gay Massage by Bruno in Dallas',
    public: true,
  },
  bio_short: {
    label: 'Short Bio',
    type: 'textarea',
    placeholder: 'Professional Brazilian therapist focused on deep tissue, recovery, and relaxation.',
    public: true,
  },
  bio_full: {
    label: 'Full Description',
    type: 'richtextarea',
    placeholder: 'Full SEO rich profile description',
    public: true,
  },
  experience_start: {
    label: 'Start Year / Experience Start Date',
    type: 'date',
    public: true,
  },
  languages: {
    label: 'Languages Spoken',
    type: 'multiselect',
    options: ['English', 'Portuguese', 'Spanish', 'French', 'Italian', 'German'],
    public: true,
  },
  city: {
    label: 'City',
    type: 'select',
    public: true,
  },
  state: {
    label: 'State',
    type: 'select',
    public: true,
  },
  neighborhood: {
    label: 'Neighborhood',
    type: 'text',
    placeholder: 'Oak Lawn',
    public: true,
  },
  location_description: {
    label: 'Location Description',
    type: 'textarea',
    placeholder: 'Near Cedar Springs and Uptown Dallas',
    public: true,
  },
  zip_code: {
    label: 'ZIP Code',
    type: 'text',
    public: false,
  },
  is_mappable: {
    label: 'Show Approximate Map Area',
    type: 'boolean',
    default: true,
    public: true,
  },
  landmarks: {
    label: 'Nearby Landmarks',
    type: 'multitag',
    placeholder: 'Uptown, Turtle Creek, Highland Park',
    public: true,
  },
  offers_incall: {
    label: 'Offers In-call',
    type: 'boolean',
    default: true,
    public: true,
  },
  offers_outcall: {
    label: 'Offers Out-call',
    type: 'boolean',
    default: true,
    public: true,
  },
  outcall_radius: {
    label: 'Out-call Radius',
    type: 'number',
    suffix: 'miles',
    public: true,
  },
  service_area_cities: {
    label: 'Service Area Cities',
    type: 'multitag',
    public: true,
  },
  massage_techniques: {
    label: 'Massage Techniques',
    type: 'multiselect',
    options: [
      'Deep Tissue',
      'Swedish',
      'Sports Massage',
      'Lymphatic Drainage',
      'Myofascial Release',
      'Hot Stone',
      'Shiatsu',
      'Thai Massage',
      'Reflexology',
      'Stretching',
      'Relaxation',
      'Bodywork',
      'Trigger Point',
      'Chair Massage',
      'Brazilian Touch',
    ],
    public: true,
  },
  specialties: {
    label: 'Specialties',
    type: 'multiselect',
    options: [
      'Gay Massage',
      'LGBTQ Friendly',
      'Mens Massage',
      'Sports Recovery',
      'Relaxation',
      'Pain Relief',
      'Stress Relief',
      'Senior Massage',
      'Couples Session',
    ],
    public: true,
  },
  massage_setup: {
    label: 'Massage Setup',
    type: 'multiselect',
    options: ['Massage Table', 'Massage Chair', 'Mat Work', 'Ask Me'],
    public: true,
  },
  mobile_extras: {
    label: 'Mobile Extras',
    type: 'multiselect',
    options: [
      'Massage Table',
      'Hot Towels',
      'Music',
      'Sheets',
      'Aromatherapy',
      'Oils',
      'Bolsters',
      'Portable Speaker',
    ],
    public: true,
  },
  incall_amenities: {
    label: 'In-call Amenities',
    type: 'multiselect',
    options: [
      'Private Studio',
      'Shower',
      'Private Restroom',
      'Parking',
      'Bottled Water',
      'Drinking Water',
      'Hot Towels',
      'Candles',
      'Aromatherapy',
      'Music',
      'Heated Table',
      'Building Security',
    ],
    public: true,
  },
  additional_services: {
    label: 'Additional Services',
    type: 'multiselect',
    options: [
      'Cupping',
      'Stretching',
      'Fitness Training',
      'Breathwork',
      'Meditation',
      'Wellness Coaching',
      'Ask Me',
    ],
    public: true,
  },
  products_used: {
    label: 'Products Used',
    type: 'multitag',
    placeholder: 'Massage lotion, coconut oil',
    public: true,
  },
  products_sold: {
    label: 'Products Sold',
    type: 'multitag',
    placeholder: 'Oils, recovery tools',
    public: true,
  },
  starting_rate: {
    label: 'Starting Rate',
    type: 'number',
    prefix: '$',
    public: true,
  },
  rates_incall: {
    label: 'In-call Rates',
    type: 'repeater',
    fields: ['duration_minutes', 'price', 'display_note'],
    public: true,
  },
  rates_outcall: {
    label: 'Out-call Rates',
    type: 'repeater',
    fields: ['duration_minutes', 'price_or_label', 'display_note'],
    public: true,
  },
  discounts: {
    label: 'Regular Discounts',
    type: 'textarea',
    placeholder: 'Repeat clients, military, ask for details',
    public: true,
  },
  weekly_specials: {
    label: 'Weekly Specials',
    type: 'textarea',
    public: true,
  },
  rate_disclaimer: {
    label: 'Rate Disclaimer',
    type: 'textarea',
    placeholder: 'Longer sessions available',
    public: true,
  },
  payment_methods: {
    label: 'Payment Methods',
    type: 'multiselect',
    options: [
      'Cash',
      'Zelle',
      'Venmo',
      'Apple Pay',
      'Cash App',
      'Visa',
      'Mastercard',
      'Amex',
    ],
    public: true,
  },
  incall_hours: {
    label: 'In-call Hours',
    type: 'weekly_schedule',
    public: true,
  },
  outcall_hours: {
    label: 'Out-call Hours',
    type: 'weekly_schedule',
    public: true,
  },
  available_now: {
    label: 'Available Now',
    type: 'boolean',
    public: true,
  },
  available_today: {
    label: 'Available Today',
    type: 'boolean',
    public: true,
  },
  same_day_booking: {
    label: 'Same Day Booking',
    type: 'boolean',
    public: true,
  },
  is_traveling: {
    label: 'Currently Traveling',
    type: 'boolean',
    public: true,
  },
  travel_cities: {
    label: 'Travel Cities',
    type: 'multitag',
    public: true,
  },
  travel_dates: {
    label: 'Travel Dates',
    type: 'daterange',
    public: true,
  },
  travel_note: {
    label: 'Travel Note',
    type: 'textarea',
    placeholder: 'Visiting Houston next week',
    public: true,
  },
  years_experience: {
    label: 'Years of Experience',
    type: 'number',
    public: true,
  },
  education: {
    label: 'School / Education',
    type: 'repeater',
    fields: ['school_name', 'program_name', 'city', 'country', 'start_date', 'end_date'],
    public: true,
  },
  licenses: {
    label: 'Licenses / Certifications',
    type: 'repeater',
    fields: ['title', 'issuer', 'year'],
    public: true,
  },
  affiliations: {
    label: 'Affiliations',
    type: 'multitag',
    placeholder: 'National Association of Massage Therapists',
    public: true,
  },
  phone_number: {
    label: 'Phone Number',
    type: 'phone',
    public: false,
  },
  show_email_button: {
    label: 'Show Email Button',
    type: 'boolean',
    default: false,
    public: true,
  },
  email_address: {
    label: 'Email Address',
    type: 'email',
    public: 'conditional',
  },
  booking_link: {
    label: 'Booking Link',
    type: 'url',
    public: true,
  },
  whatsapp_number: {
    label: 'WhatsApp',
    type: 'phone',
    public: false,
  },
  telegram_handle: {
    label: 'Telegram',
    type: 'text',
    public: 'optional',
  },
  profile_photo: {
    label: 'Profile Photo',
    type: 'image',
    public: true,
  },
  gallery_photos: {
    label: 'Gallery Photos',
    type: 'multiimage',
    public: true,
  },
  cover_photo: {
    label: 'Cover Photo',
    type: 'image',
    public: true,
  },
  video_intro: {
    label: 'Intro Video',
    type: 'url',
    public: 'optional',
  },
  tier: {
    label: 'Membership Tier',
    type: 'select',
    options: ['Free', 'Standard', 'Pro', 'Elite'],
    public: true,
  },
  is_verified_profile: {
    label: 'Verified Profile',
    type: 'boolean',
    public: true,
  },
  lgbtq_friendly: {
    label: 'LGBTQ Friendly',
    type: 'boolean',
    public: true,
  },
  visiting_soon: {
    label: 'Visiting Soon',
    type: 'boolean',
    public: true,
  },
  top_rated: {
    label: 'Top Rated',
    type: 'boolean',
    public: true,
  },
  seo_title: {
    label: 'SEO Title',
    type: 'text',
    public: false,
  },
  seo_description: {
    label: 'SEO Description',
    type: 'textarea',
    public: false,
  },
  seo_keywords: {
    label: 'SEO Keywords',
    type: 'multitag',
    public: false,
  },
  slug: {
    label: 'Profile Slug',
    type: 'text',
    public: true,
  },
  canonical_city: {
    label: 'Canonical City',
    type: 'text',
    public: false,
  },
};
