// Steps definition for onboarding forms
export const MASSAGE_THERAPIST_ONBOARDING_STEPS = [
  {
    key: 'basics',
    label: 'Basic Info',
    fields: [
      'full_name',
      'display_name',
      'headline',
      'bio_short',
      'bio_full',
      'experience_start',
      'languages',
    ],
  },
  {
    key: 'location',
    label: 'Location',
    fields: [
      'city',
      'state',
      'neighborhood',
      'location_description',
      'zip_code',
      'is_mappable',
      'landmarks',
    ],
  },
  {
    key: 'appointment_types',
    label: 'Appointment Types',
    fields: [
      'offers_incall',
      'offers_outcall',
      'outcall_radius',
      'service_area_cities',
    ],
  },
  {
    key: 'services',
    label: 'Services',
    fields: [
      'massage_techniques',
      'specialties',
      'massage_setup',
      'mobile_extras',
      'incall_amenities',
      'additional_services',
      'products_used',
      'products_sold',
    ],
  },
  {
    key: 'pricing',
    label: 'Pricing',
    fields: [
      'starting_rate',
      'rates_incall',
      'rates_outcall',
      'discounts',
      'weekly_specials',
      'rate_disclaimer',
      'payment_methods',
    ],
  },
  {
    key: 'availability',
    label: 'Availability',
    fields: [
      'incall_hours',
      'outcall_hours',
      'available_now',
      'available_today',
      'same_day_booking',
    ],
  },
  {
    key: 'travel',
    label: 'Travel',
    fields: [
      'is_traveling',
      'travel_cities',
      'travel_dates',
      'travel_note',
    ],
  },
  {
    key: 'professional_info',
    label: 'Professional Info',
    fields: [
      'years_experience',
      'education',
      'licenses',
      'affiliations',
    ],
  },
  {
    key: 'contact',
    label: 'Contact Options',
    fields: [
      'phone_number',
      'show_email_button',
      'email_address',
      'booking_link',
      'whatsapp_number',
      'telegram_handle',
    ],
  },
  {
    key: 'photos',
    label: 'Photos',
    fields: [
      'profile_photo',
      'gallery_photos',
      'cover_photo',
      'video_intro',
    ],
  },
  {
    key: 'trust',
    label: 'Profile Visibility',
    fields: [
      'tier',
      'is_verified_profile',
      'lgbtq_friendly',
      'visiting_soon',
      'top_rated',
    ],
  },
  {
    key: 'seo',
    label: 'SEO Preview',
    fields: [
      'seo_title',
      'seo_description',
      'seo_keywords',
      'slug',
      'canonical_city',
    ],
  },
];
