import { useState, useEffect } from "react";
import { useProfile } from "@/hooks/useProfile";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
import { Loader2, Save, Sparkles, MessageCircleQuestion, CheckCircle2 } from "lucide-react";

const PREMADE_QUESTIONS = [
  "What types of massage do you specialize in?",
  "What should I expect during my first session?",
  "How do I book an appointment?",
  "What are your cancellation policies?",
  "Do you offer outcall / mobile services?",
  "Is your space LGBTQ+ friendly and inclusive?",
  "What certifications or training do you have?",
  "How long are your sessions?",
  "What should I wear or bring to a session?",
  "Do you offer couples or group sessions?",
];

interface FAQItem {
  question: string;
  answer: string;
}

const DashboardFAQ = () => {
  const { profile, loading, updateProfile } = useProfile();
  const { toast } = useToast();
  const [saving, setSaving] = useState(false);
  const [generatingIdx, setGeneratingIdx] = useState<number | null>(null);
  const [faqs, setFaqs] = useState<FAQItem[]>(
    PREMADE_QUESTIONS.map((q) => ({ question: q, answer: "" }))
  );

  useEffect(() => {
    if (profile?.custom_faq) {
      const saved = profile.custom_faq as unknown as FAQItem[];
      if (Array.isArray(saved)) {
        setFaqs(
          PREMADE_QUESTIONS.map((q) => {
            const existing = saved.find((s) => s.question === q);
            return { question: q, answer: existing?.answer || "" };
          })
        );
      }
    }
  }, [profile]);

  const handleSave = async () => {
    setSaving(true);
    const toSave = faqs.filter((f) => f.answer.trim());
    const { error } = await updateProfile({ custom_faq: toSave as any });
    setSaving(false);
    toast({
      title: error ? "Error saving" : "FAQ updated",
      description: error?.message || "Your Q&A has been saved.",
      variant: error ? "destructive" : "default",
    });
  };

  const generateAnswer = async (idx: number) => {
    setGeneratingIdx(idx);
    try {
      const profileContext = profile
        ? `Name: ${profile.display_name || profile.full_name}. Bio: ${profile.bio || "N/A"}. Specialties: ${(profile.specialties || []).join(", ") || "N/A"}. City: ${profile.city || "N/A"}. Languages: ${(profile.languages || []).join(", ") || "N/A"}.`
        : "";

      const { data, error } = await supabase.functions.invoke("generate-faq-answer", {
        body: { question: faqs[idx].question, profileContext },
      });

      if (error) throw error;

      if (data?.error) {
        toast({ title: "AI Error", description: data.error, variant: "destructive" });
      } else if (data?.answer) {
        setFaqs((prev) =>
          prev.map((f, i) => (i === idx ? { ...f, answer: data.answer } : f))
        );
        toast({ title: "Answer generated by Knotty ✨" });
      }
    } catch (err: any) {
      toast({ title: "Error", description: err.message || "Failed to generate answer", variant: "destructive" });
    } finally {
      setGeneratingIdx(null);
    }
  };

  if (loading) return <div className="animate-pulse space-y-4"><div className="h-8 bg-muted rounded w-1/3" /><div className="h-40 bg-muted rounded" /></div>;

  const answeredCount = faqs.filter((f) => f.answer.trim()).length;

  return (
    <div className="max-w-3xl space-y-8">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold flex items-center gap-2">
            <MessageCircleQuestion className="w-6 h-6" />
            Q&A
          </h1>
          <p className="text-sm text-muted-foreground">
            Answer frequently asked questions for your public profile ({answeredCount}/{PREMADE_QUESTIONS.length} answered)
          </p>
        </div>
        <Button onClick={handleSave} disabled={saving}>
          {saving ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Save className="w-4 h-4 mr-2" />}
          Save
        </Button>
      </div>

      <div className="space-y-4">
        {faqs.map((faq, idx) => (
          <section key={idx} className="glass-card p-5 space-y-3">
            <div className="flex items-start justify-between gap-3">
              <div className="flex items-start gap-2 flex-1">
                <span className="text-xs font-bold text-muted-foreground bg-secondary rounded-full w-6 h-6 flex items-center justify-center shrink-0 mt-0.5">
                  {idx + 1}
                </span>
                <h3 className="text-sm font-semibold leading-snug">{faq.question}</h3>
              </div>
              {faq.answer.trim() && (
                <CheckCircle2 className="w-4 h-4 text-success shrink-0 mt-0.5" />
              )}
            </div>

            <Textarea
              value={faq.answer}
              onChange={(e) =>
                setFaqs((prev) =>
                  prev.map((f, i) => (i === idx ? { ...f, answer: e.target.value } : f))
                )
              }
              placeholder="Write your answer here..."
              className="min-h-[80px] text-sm"
            />

            <Button
              variant="outline"
              size="sm"
              onClick={() => generateAnswer(idx)}
              disabled={generatingIdx !== null}
              className="gap-2"
            >
              {generatingIdx === idx ? (
                <Loader2 className="w-3.5 h-3.5 animate-spin" />
              ) : (
                <Sparkles className="w-3.5 h-3.5" />
              )}
              {generatingIdx === idx ? "Knotty is writing..." : "Ask Knotty to write"}
            </Button>
          </section>
        ))}
      </div>
    </div>
  );
};

export default DashboardFAQ;
