export interface FieldConfig {
  name: string;
  label: string;
  type: "text" | "number" | "boolean" | "array" | "json" | "date";
  description?: string;
}

export const PROFILE_FIELDS_BY_SECTION: Record<string, string[]> = {
  "Basic Information": [
    "id",
    "user_id",
    "display_name",
    "full_name",
    "email",
    "email_address",
    "phone",
    "phone_number",
    "slug",
    "avatar_url",
    "photo_url",
    "headline",
    "tagline",
    "bio",
  ],
  Location: [
    "city",
    "state",
    "country",
    "zip_code",
    "latitude",
    "longitude",
    "street_reference",
    "neighborhood",
    "neighborhood_name",
    "canonical_city_slug",
    "primary_area",
    "location_type",
    "location_marker_type",
    "map_enabled",
  ],
  Professional: [
    "years_experience",
    "start_year",
    "specialties",
    "specialty",
    "modalities",
    "modality",
    "languages",
    "languages_spoken",
    "certifications",
    "education",
    "education_entries",
    "training",
    "affiliations",
    "massage_techniques",
    "areas_served",
    "keyword_slugs",
    "segments",
  ],
  Availability: [
    "available_now",
    "available_now_expires",
    "business_hours",
    "mobile_hours",
    "studio_hours",
    "travel_schedule",
    "traveling",
    "visiting",
    "business_trips",
  ],
  "Services & Pricing": [
    "incall",
    "outcall",
    "offers_incall",
    "offers_outcall",
    "incall_price",
    "outcall_price",
    "incall_details",
    "outcall_details",
    "outcall_radius",
    "outcall_radius_miles",
    "service_radius_km",
    "service_radius_miles",
    "price_min",
    "price_max",
    "starting_price",
    "starting_rate",
    "booking_url",
    "booking_link",
    "booking_platform",
    "website",
  ],
  "Verification & Status": [
    "is_verified_email",
    "is_verified_phone",
    "is_verified_photos",
    "is_verified_profile",
    "is_verified_identity",
    "identity_verified_at",
    "age_conduct_attested_at",
    "profile_status",
    "verification_status",
    "moderation_status",
    "account_status",
    "current_status",
    "approved_at",
    "approved_by",
    "rejected_at",
    "rejected_by",
    "rejection_reason",
  ],
  "Account & Subscription": [
    "account_status",
    "subscription_status",
    "subscription_tier",
    "subscription_plan",
    "_tier",
    "is_active",
    "is_banned",
    "is_suspended",
    "is_featured",
    "is_demo",
    "banned_reason",
    "suspension_reason",
    "stripe_customer_id",
    "stripe_subscription_id",
    "stripe_verification_session_id",
    "subscription_cancel_at_period_end",
    "subscription_current_period_start",
    "subscription_current_period_end",
    "current_period_end",
    "featured_until",
  ],
  "Payment & Discounts": [
    "payment_methods",
    "day_of_week_discount",
    "regular_discounts",
    "weekly_special",
    "promotions",
    "rate_disclaimers",
    "pricing_sessions",
  ],
  Media: [
    "presentation_video_url",
    "photo_limit",
    "social_media",
  ],
  "Services & Setup": [
    "massage_setup",
    "incall_amenities",
    "mobile_extras",
    "accessibility_features",
    "studio_amenities",
    "products_used",
    "products_sold",
    "additional_services",
    "service_categories",
    "add_ons",
  ],
  "Ratings & Reviews": [
    "average_rating",
    "rating_average",
    "review_count",
    "profile_views",
    "view_count",
    "contact_clicks",
    "inquiry_count",
  ],
  "SEO & Content": [
    "seo_title",
    "seo_description",
    "seo_keywords",
    "custom_faq",
    "rates",
  ],
  "Administrative": [
    "admin_notes",
    "moderation_notes",
    "role",
    "completion_percentage",
    "completion_score",
    "profile_completeness",
    "profile_completion_score",
    "lgbtq_affirming",
    "accepts_all_genders",
    "gender",
    "height_inches",
    "weight_lb",
    "body_type",
    "visibility_level",
    "visibility_status",
    "session_duration",
    "session_lengths",
  ],
  Metadata: [
    "created_at",
    "updated_at",
    "submitted_at",
    "last_active_at",
    "last_seen_at",
    "reviewed_at",
    "reviewed_by",
    "availability_note",
    "show_email",
    "whatsapp",
    "whatsapp_number",
  ],
};

export const FIELD_TYPES: Record<string, "text" | "number" | "boolean" | "array" | "json" | "date"> = {
  // Text fields
  display_name: "text",
  full_name: "text",
  email: "text",
  email_address: "text",
  phone: "text",
  phone_number: "text",
  slug: "text",
  city: "text",
  state: "text",
  country: "text",
  zip_code: "text",
  headline: "text",
  tagline: "text",
  bio: "text",
  street_reference: "text",
  neighborhood: "text",
  neighborhood_name: "text",
  canonical_city_slug: "text",
  primary_area: "text",
  location_type: "text",
  location_marker_type: "text",
  specialty: "text",
  modality: "text",
  education: "text",
  training: "text",
  booking_link: "text",
  booking_platform: "text",
  website: "text",
  profile_status: "text",
  verification_status: "text",
  moderation_status: "text",
  account_status: "text",
  current_status: "text",
  rejection_reason: "text",
  banned_reason: "text",
  suspension_reason: "text",
  stripe_customer_id: "text",
  stripe_subscription_id: "text",
  stripe_verification_session_id: "text",
  subscription_status: "text",
  subscription_tier: "text",
  subscription_plan: "text",
  _tier: "text",
  admin_notes: "text",
  moderation_notes: "text",
  role: "text",
  availability_note: "text",
  seo_title: "text",
  seo_description: "text",
  incall_details: "text",
  outcall_details: "text",
  presentation_video_url: "text",
  whatsapp: "text",
  whatsapp_number: "text",
  certifications: "text",
  user_id: "text",
  id: "text",
  avatar_url: "text",
  photo_url: "text",
  booking_url: "text",

  // Number fields
  incall_price: "number",
  outcall_price: "number",
  price_min: "number",
  price_max: "number",
  starting_price: "number",
  starting_rate: "number",
  years_experience: "number",
  start_year: "number",
  latitude: "number",
  longitude: "number",
  outcall_radius: "number",
  outcall_radius_miles: "number",
  service_radius_km: "number",
  service_radius_miles: "number",
  height_inches: "number",
  weight_lb: "number",
  visibility_level: "number",
  session_duration: "number",
  average_rating: "number",
  rating_average: "number",
  review_count: "number",
  profile_views: "number",
  view_count: "number",
  contact_clicks: "number",
  inquiry_count: "number",
  completion_percentage: "number",
  completion_score: "number",
  profile_completeness: "number",
  profile_completion_score: "number",
  photo_limit: "number",

  // Boolean fields
  is_verified_email: "boolean",
  is_verified_phone: "boolean",
  is_verified_photos: "boolean",
  is_verified_profile: "boolean",
  is_verified_identity: "boolean",
  is_active: "boolean",
  is_banned: "boolean",
  is_suspended: "boolean",
  is_featured: "boolean",
  is_demo: "boolean",
  incall: "boolean",
  outcall: "boolean",
  offers_incall: "boolean",
  offers_outcall: "boolean",
  available_now: "boolean",
  traveling: "boolean",
  visiting: "boolean",
  map_enabled: "boolean",
  lgbtq_affirming: "boolean",
  accepts_all_genders: "boolean",
  show_email: "boolean",
  subscription_cancel_at_period_end: "boolean",

  // Array fields
  specialties: "array",
  languages: "array",
  languages_spoken: "array",
  modalities: "array",
  areas_served: "array",
  keyword_slugs: "array",
  segments: "array",
  incall_amenities: "array",
  mobile_extras: "array",
  accessibility_features: "array",
  studio_amenities: "array",
  products_used: "array",
  products_sold: "array",
  additional_services: "array",
  service_categories: "array",
  payment_methods: "array",
  rate_disclaimers: "array",
  session_lengths: "array",
  seo_keywords: "array",
  massage_techniques: "array",
  massage_setup: "array",
  affiliations: "array",

  // JSON fields
  add_ons: "json",
  business_hours: "json",
  mobile_hours: "json",
  studio_hours: "json",
  travel_schedule: "json",
  business_trips: "json",
  day_of_week_discount: "json",
  regular_discounts: "json",
  weekly_special: "json",
  promotions: "json",
  pricing_sessions: "json",
  rates: "json",
  social_media: "json",
  custom_faq: "json",
  education_entries: "json",

  // Date fields
  created_at: "date",
  updated_at: "date",
  submitted_at: "date",
  approved_at: "date",
  rejected_at: "date",
  last_active_at: "date",
  last_seen_at: "date",
  reviewed_at: "date",
  age_conduct_attested_at: "date",
  identity_verified_at: "date",
  featured_until: "date",
  available_now_expires: "date",
  subscription_current_period_start: "date",
  subscription_current_period_end: "date",
  current_period_end: "date",
};
