import type { Metadata } from "next";
import Link from "next/link";
import { Bot, Info, MessageCircle, TriangleAlert } from "lucide-react";

import { JsonLd } from "@/app/_components/json-ld";
import { buildBreadcrumbJsonLd, createPageMetadata } from "@/app/_lib/seo";

export const metadata: Metadata = createPageMetadata({
  title: "AI Assistant Disclosure — Knotty AI",
  description:
    "How Knotty AI works on MasseurMatch, what AI responses can and cannot be used for, and your responsibilities when using AI-assisted features.",
  path: "/ai-disclosure",
  keywords: ["AI disclosure", "Knotty AI", "AI assistant terms", "AI limitations"],
});

const limitations = [
  {
    heading: "AI responses may be inaccurate",
    body: "AI-generated responses are generated by language models that can produce incorrect, outdated, or misleading information. Always independently verify important information before acting on it.",
  },
  {
    heading: "Not professional advice",
    body: "Knotty AI does not provide legal, medical, safety, licensing, tax, financial, or professional advice of any kind. Nothing Knotty AI says should be treated as a substitute for professional consultation.",
  },
  {
    heading: "Not a safety guarantee",
    body: "Knotty AI cannot verify provider credentials, conduct background checks, or assess personal safety situations. Do not rely on AI responses to evaluate whether a provider is safe, licensed, or appropriate for your needs.",
  },
  {
    heading: "Not always up to date",
    body: "AI models have knowledge cutoffs and may not reflect the most recent licensing laws, regulations, pricing, or platform updates. Check official sources for time-sensitive information.",
  },
  {
    heading: "Not emergency services",
    body: "If you are in immediate danger or experiencing an emergency, contact local emergency services. Knotty AI is not a crisis resource, hotline, or emergency response system.",
  },
  {
    heading: "Responses may be inappropriate",
    body: "Despite guardrails and safety filters, AI systems may occasionally produce responses that are unhelpful, off-topic, or inappropriate. Please use your own judgment when evaluating AI output.",
  },
];

export default function AiDisclosurePage() {
  return (
    <>
      <JsonLd
        data={buildBreadcrumbJsonLd([
          { name: "Home", path: "/" },
          { name: "AI Disclosure", path: "/ai-disclosure" },
        ])}
      />

      <div className="page-shell py-10">
        <section className="rounded-3xl border border-border-subtle bg-[linear-gradient(135deg,rgba(255,255,255,0.98),rgba(244,246,250,0.96))] p-6 shadow-brand sm:p-8">
          <p className="text-xs font-semibold uppercase tracking-[0.28em] text-text-muted">AI Features</p>
          <h1 className="mt-3 max-w-3xl font-display text-4xl font-semibold tracking-tight text-foreground sm:text-5xl">
            AI Assistant Disclosure
          </h1>
          <p className="mt-4 max-w-3xl text-base leading-7 text-text-secondary">
            MasseurMatch includes Knotty AI, an artificial intelligence assistant designed to help users discover
            providers and navigate the platform. This page explains what Knotty AI is, what it can do, what it
            cannot do, and your responsibilities when using it.
          </p>
          <p className="mt-3 text-xs text-text-muted">Last updated: June 29, 2026</p>
        </section>

        <section className="mt-8 premium-surface rounded-3xl border border-border-subtle p-6 shadow-brand sm:p-8">
          <div className="flex items-start gap-4">
            <div className="inline-flex h-12 w-12 flex-none items-center justify-center rounded-2xl bg-brand-secondary/10 text-brand-secondary">
              <Bot className="h-6 w-6" strokeWidth={2.25} />
            </div>
            <div>
              <h2 className="font-display text-2xl font-semibold tracking-tight text-foreground">What is Knotty AI?</h2>
              <div className="mt-4 space-y-3 text-sm leading-7 text-text-secondary">
                <p>
                  Knotty AI is an AI-powered assistant integrated into the MasseurMatch platform. It uses large
                  language models to answer questions about the directory, help users find relevant providers,
                  explain how the platform works, and offer general wellness discovery guidance.
                </p>
                <p>
                  Knotty AI is built to serve as a helpful starting point for discovery — not as a source of
                  authoritative advice or verified information.
                </p>
              </div>
            </div>
          </div>
        </section>

        <section className="mt-8">
          <h2 className="mb-5 font-display text-2xl font-semibold tracking-tight text-foreground">
            Important limitations
          </h2>
          <div className="grid gap-4 md:grid-cols-2">
            {limitations.map((item) => (
              <div
                key={item.heading}
                className="premium-surface rounded-3xl border border-border-subtle p-5 shadow-soft"
              >
                <div className="flex items-start gap-3">
                  <TriangleAlert className="mt-0.5 h-4 w-4 flex-none text-amber-500" strokeWidth={2.25} />
                  <div>
                    <h3 className="font-display text-base font-semibold text-foreground">{item.heading}</h3>
                    <p className="mt-2 text-sm leading-6 text-text-secondary">{item.body}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </section>

        <section className="mt-8 premium-surface rounded-3xl border border-border-subtle p-6 shadow-brand sm:p-8">
          <div className="flex items-start gap-4">
            <Info className="mt-0.5 h-5 w-5 flex-none text-brand-secondary" strokeWidth={2.25} />
            <div>
              <h2 className="font-display text-xl font-semibold tracking-tight text-foreground">Your responsibility</h2>
              <div className="mt-4 space-y-3 text-sm leading-7 text-text-secondary">
                <p>
                  You are responsible for independently verifying any important information before making
                  decisions based on AI responses. This includes verifying provider credentials, licensing,
                  pricing, availability, safety, and suitability.
                </p>
                <p>
                  AI-generated suggestions are informational starting points only. They are not endorsements,
                  recommendations, guarantees, or assessments of any individual provider.
                </p>
              </div>
            </div>
          </div>
        </section>

        <section className="mt-8 premium-surface rounded-3xl border border-border-subtle p-6 shadow-brand sm:p-8">
          <div className="flex items-start gap-4">
            <MessageCircle className="mt-0.5 h-5 w-5 flex-none text-brand-secondary" strokeWidth={2.25} />
            <div>
              <h2 className="font-display text-xl font-semibold tracking-tight text-foreground">Data and privacy</h2>
              <div className="mt-4 space-y-3 text-sm leading-7 text-text-secondary">
                <p>
                  Conversations with Knotty AI may be processed to operate, improve, monitor, and secure the
                  AI service. AI interaction data is handled in accordance with our{" "}
                  <Link href="/privacy" className="text-brand-secondary underline hover:text-brand-primary">Privacy Policy</Link>.
                </p>
                <p>
                  Do not share sensitive personal information — such as passwords, financial account details,
                  or private health information — with Knotty AI. AI conversations are not a secure channel for
                  transmitting confidential data.
                </p>
              </div>
            </div>
          </div>
        </section>

        <section className="mt-8 rounded-3xl border border-border-subtle bg-brand-primary px-6 py-7 text-white shadow-brand sm:px-8">
          <p className="text-xs font-semibold uppercase tracking-[0.28em] text-brand-soft">Related Policies</p>
          <div className="mt-5 flex flex-wrap gap-3 text-sm font-semibold">
            {[
              { href: "/privacy", label: "Privacy Policy" },
              { href: "/terms", label: "Terms of Service" },
              { href: "/platform-disclaimer", label: "Platform Disclaimer" },
              { href: "/acceptable-use", label: "Acceptable Use" },
            ].map((link) => (
              <Link
                key={link.href}
                href={link.href}
                className="rounded-full border border-white/18 bg-white/8 px-4 py-2 text-white transition hover:border-white/32 hover:bg-white/12"
              >
                {link.label}
              </Link>
            ))}
          </div>
        </section>
      </div>
    </>
  );
}
