-- Insert Bruno's profile into the profiles table
-- This will make him available via the dynamic [slug] route and in the sitemap

INSERT INTO profiles (
  id,
  slug,
  display_name,
  full_name,
  city,
  neighborhood_name,
  primary_area,
  bio,
  avatar_url,
  specialties,
  modality,
  _tier,
  status,
  is_active,
  incall_price,
  outcall_price,
  years_experience,
  lgbtq_affirming,
  accepts_all_genders,
  languages_spoken,
  is_verified_identity,
  is_verified_profile,
  custom_faq,
  pricing_sessions,
  business_hours,
  created_at,
  updated_at
) VALUES (
  gen_random_uuid(),
  'bruno-dallas-tx',
  'Bruno',
  'Bruno Martinez',
  'Dallas',
  'Oak Lawn',
  'Uptown Dallas',
  'Professional licensed massage therapist specializing in deep tissue and therapeutic massage in the heart of Dallas. With over 8 years of experience, I create a welcoming, judgment-free environment for all clients. My approach combines traditional Swedish techniques with targeted deep tissue work to address your specific needs, whether that''s stress relief, muscle recovery, or chronic pain management. I take pride in providing a safe, affirming space for the LGBTQ+ community.',
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face',
  ARRAY['Deep Tissue', 'Swedish', 'Sports Massage', 'Therapeutic', 'Relaxation'],
  'Licensed Massage Therapist',
  'pro',
  'active',
  true,
  120,
  150,
  8,
  true,
  true,
  ARRAY['English', 'Spanish'],
  true,
  true,
  '[
    {"question": "What should I expect during my first session?", "answer": "During your first visit, we will discuss your goals, any areas of concern, and your preferred pressure level. The session is tailored entirely to your needs."},
    {"question": "Do you offer outcall services?", "answer": "Yes, I offer mobile massage services throughout the Dallas area including Oak Lawn, Uptown, Downtown, and surrounding neighborhoods."},
    {"question": "What is your cancellation policy?", "answer": "I require 24 hours notice for cancellations. Late cancellations may be subject to a fee."}
  ]'::jsonb,
  '[
    {"name": "Relaxation Session", "duration": 60, "incall": 120, "outcall": 150},
    {"name": "Deep Tissue Session", "duration": 60, "incall": 130, "outcall": 160},
    {"name": "Extended Session", "duration": 90, "incall": 170, "outcall": 210}
  ]'::jsonb,
  '{
    "monday": {"open": "10:00", "close": "20:00"},
    "tuesday": {"open": "10:00", "close": "20:00"},
    "wednesday": {"open": "10:00", "close": "20:00"},
    "thursday": {"open": "10:00", "close": "20:00"},
    "friday": {"open": "10:00", "close": "21:00"},
    "saturday": {"open": "11:00", "close": "18:00"},
    "sunday": {"open": "12:00", "close": "17:00"}
  }'::jsonb,
  NOW(),
  NOW()
)
ON CONFLICT (slug) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  full_name = EXCLUDED.full_name,
  city = EXCLUDED.city,
  neighborhood_name = EXCLUDED.neighborhood_name,
  primary_area = EXCLUDED.primary_area,
  bio = EXCLUDED.bio,
  avatar_url = EXCLUDED.avatar_url,
  specialties = EXCLUDED.specialties,
  modality = EXCLUDED.modality,
  _tier = EXCLUDED._tier,
  status = EXCLUDED.status,
  is_active = EXCLUDED.is_active,
  incall_price = EXCLUDED.incall_price,
  outcall_price = EXCLUDED.outcall_price,
  years_experience = EXCLUDED.years_experience,
  lgbtq_affirming = EXCLUDED.lgbtq_affirming,
  accepts_all_genders = EXCLUDED.accepts_all_genders,
  languages_spoken = EXCLUDED.languages_spoken,
  is_verified_identity = EXCLUDED.is_verified_identity,
  is_verified_profile = EXCLUDED.is_verified_profile,
  custom_faq = EXCLUDED.custom_faq,
  pricing_sessions = EXCLUDED.pricing_sessions,
  business_hours = EXCLUDED.business_hours,
  updated_at = NOW();
