-- Ensure all columns required by the migration chain exist on profiles.
-- The original table was created manually in production with a full schema;
-- this file backfills any columns that the minimal baseline migration omitted
-- so that subsequent migrations can safely create indexes and alter tables.

alter table public.profiles
  add column if not exists display_name          text,
  add column if not exists phone                 text,
  add column if not exists bio                   text,
  add column if not exists photo_url             text,
  add column if not exists city                  text,
  add column if not exists state                 text,
  add column if not exists country               text default 'US',
  add column if not exists specialties           text[] default '{}',
  add column if not exists modalities            text[] default '{}',
  add column if not exists languages             text[] default '{English}',
  add column if not exists incall                boolean default true,
  add column if not exists outcall               boolean default false,
  add column if not exists traveling             boolean default false,
  add column if not exists visiting              boolean default false,
  add column if not exists price_min             integer,
  add column if not exists price_max             integer,
  add column if not exists session_duration      integer default 60,
  add column if not exists available_now         boolean default false,
  add column if not exists is_verified_identity  boolean default false,
  add column if not exists is_verified_email     boolean default false,
  add column if not exists is_verified_phone     boolean default false,
  add column if not exists subscription_tier     text default 'free',
  add column if not exists subscription_status   text default 'active',
  add column if not exists stripe_customer_id    text,
  add column if not exists profile_status        text default 'draft',
  add column if not exists visibility_status     text default 'hidden',
  add column if not exists is_active             boolean default false,
  add column if not exists is_featured           boolean default false,
  add column if not exists is_suspended          boolean default false,
  add column if not exists is_banned             boolean default false,
  add column if not exists profile_completeness  integer default 0,
  add column if not exists view_count            integer default 0,
  add column if not exists inquiry_count         integer default 0,
  add column if not exists review_count          integer default 0,
  add column if not exists average_rating        numeric(3,2),
  add column if not exists latitude              double precision,
  add column if not exists longitude             double precision,
  add column if not exists boost_score           integer default 0,
  add column if not exists featured_until        timestamptz,
  add column if not exists approved_at           timestamptz,
  add column if not exists last_active_at        timestamptz;
