-- Add all remaining profiles columns referenced across the migration chain.
-- Covers every column in PRODUCTION_SCHEMA_LOCK.sql not yet present so that
-- RPC functions, indexes, and ALTER statements in later migrations all succeed.

alter table public.profiles
  add column if not exists slug                            text,
  add column if not exists avatar_url                     text,
  add column if not exists headline                       text,
  add column if not exists neighborhood                   text,
  add column if not exists neighborhood_name              text,
  add column if not exists primary_area                   text,
  add column if not exists email_address                  text,
  add column if not exists phone_number                   text,
  add column if not exists whatsapp                       text,
  add column if not exists whatsapp_number                text,
  add column if not exists website                        text,
  add column if not exists booking_link                   text,
  add column if not exists specialty                      text,
  add column if not exists modality                       text,
  add column if not exists massage_techniques             text[] default '{}',
  add column if not exists service_categories             text[] default '{}',
  add column if not exists languages_spoken               text[] default '{}',
  add column if not exists offers_incall                  boolean default false,
  add column if not exists offers_outcall                 boolean default false,
  add column if not exists starting_price                 integer,
  add column if not exists starting_rate                  integer,
  add column if not exists incall_price                   integer,
  add column if not exists outcall_price                  integer,
  add column if not exists session_lengths                integer[] default '{}',
  add column if not exists outcall_radius                 integer,
  add column if not exists outcall_radius_miles           integer,
  add column if not exists location_type                  text default 'incall',
  add column if not exists available_now_expires          timestamptz,
  add column if not exists business_hours                 jsonb,
  add column if not exists custom_faq                     jsonb,
  add column if not exists promotions                     jsonb,
  add column if not exists travel_schedule                jsonb,
  add column if not exists areas_served                   text[] default '{}',
  add column if not exists training                       text,
  add column if not exists education                      text,
  add column if not exists certifications                 text,
  add column if not exists years_experience               integer,
  add column if not exists height_inches                  integer,
  add column if not exists weight_lb                      integer,
  add column if not exists body_type                      text,
  add column if not exists start_year                     integer,
  add column if not exists lgbtq_affirming                boolean default false,
  add column if not exists accepts_all_genders            boolean default true,
  add column if not exists accessibility_features         text[] default '{}',
  add column if not exists is_verified_profile            boolean default false,
  add column if not exists is_verified_photos             boolean default false,
  add column if not exists verification_status            text default 'unverified',
  add column if not exists _tier                          text,
  add column if not exists photo_limit                    integer default 2,
  add column if not exists visibility_level               integer default 1,
  add column if not exists seo_title                      text,
  add column if not exists seo_description                text,
  add column if not exists seo_keywords                   text[],
  add column if not exists completion_score               integer default 0,
  add column if not exists profile_views                  integer default 0,
  add column if not exists contact_clicks                 integer default 0,
  add column if not exists terms_accepted_at              timestamptz,
  add column if not exists add_ons                        jsonb,
  add column if not exists pricing_sessions               jsonb,
  add column if not exists rates                          jsonb,
  add column if not exists rating_average                 numeric(3,2),
  add column if not exists presentation_video_url         text,
  add column if not exists social_media                   jsonb,
  add column if not exists subscription_plan              text,
  add column if not exists subscription_current_period_start timestamptz,
  add column if not exists subscription_current_period_end   timestamptz,
  add column if not exists subscription_cancel_at_period_end boolean default false,
  add column if not exists completion_percentage          integer default 0,
  add column if not exists submitted_at                   timestamptz,
  add column if not exists rejected_at                    timestamptz,
  add column if not exists rejected_by                    uuid references auth.users(id) on delete set null,
  add column if not exists reviewed_at                    timestamptz,
  add column if not exists reviewed_by                    uuid references auth.users(id) on delete set null,
  add column if not exists admin_notes                    text,
  add column if not exists moderation_notes               text,
  add column if not exists rejection_reason               text,
  add column if not exists stripe_subscription_id         text,
  add column if not exists stripe_verification_session_id text,
  add column if not exists current_period_end             timestamptz;
