-- Historical migration marker.
-- The previous implementation deleted rows from supabase_migrations.schema_migrations,
-- which makes migration history non-deterministic for fresh environments.
-- Reverted migrations are represented by explicit no-op marker files instead.
