// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const runtimeProcess = globalThis as {
  process?: {
    env?: Record<string, string | undefined>;
  };
};

const processEnv = runtimeProcess.process?.env ?? {};

const SUPABASE_URL =
  processEnv.VITE_SUPABASE_URL ||
  processEnv.NEXT_PUBLIC_SUPABASE_URL ||
  processEnv.SUPABASE_URL ||
  "";

const SUPABASE_PUBLISHABLE_KEY =
  processEnv.VITE_SUPABASE_PUBLISHABLE_KEY ||
  processEnv.NEXT_PUBLIC_SUPABASE_ANON_KEY ||
  processEnv.SUPABASE_ANON_KEY ||
  "";

const browserStorage = typeof window === "undefined" ? undefined : window.localStorage;
const isBrowser = typeof window !== "undefined";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: browserStorage,
    persistSession: isBrowser,
    autoRefreshToken: isBrowser,
  }
});
